"""Stable positional API boundary; internal callers use named request values."""

from dataclasses import dataclass, replace
from typing import Any

GENERATION_FIELDS = (
    "mode",
    "model_profile",
    "text_encoder",
    "stage_model_offload",
    "generation_mode",
    "turbo_variant",
    "prompt",
    "first_image",
    "last_image",
    "ref_image_1",
    "ref_image_2",
    "ref_image_3",
    "ref_image_4",
    "ref_image_5",
    "ref_image_6",
    "ref_image_7",
    "ref_image_8",
    "ref_image_9",
    "ref_video_1",
    "ref_video_2",
    "ref_video_3",
    "ref_audio_1",
    "ref_audio_2",
    "ref_audio_3",
    "duration",
    "width",
    "height",
    "steps",
    "scheduler",
    "seed",
    "attention_mode",
    "sla_preset",
    "sol_tau",
    "sol_thresh_type",
    "sol_exact_mode",
    "sol_dense_steps",
    "sol_step_off",
    "sol_sink_tokens",
    "cache_mode",
    "fbcache_preset",
    "fbcache_threshold",
    "fbcache_start",
    "fbcache_end",
    "fbcache_max_hits",
    "fbcache_temporal_guard",
    "easycache_threshold",
    "easycache_start",
    "easycache_end",
    "easycache_verbose",
    "ref_image_size",
    "postprocess",
    "reuse_unchanged_inputs",
    "latent_upscale",
    "latent_upscaler_model",
    "latent_upscale_refine_steps",
    "latent_upscale_method",
    "latent_split_tile_width",
    "latent_split_tile_height",
    "latent_split_overlap_ratio",
    "latent_split_fade_ratio",
    "latent_split_chunk_frames",
    "latent_split_temporal_overlap_frames",
    "latent_split_seam_denoise",
    "latent_split_seam_polish",
    "upscale_force_offload",
    "upscale_split_enabled",
    "upscale_split_seconds",
    "upscale_resolution",
    "seedvr2_model",
    "ltx25_model",
    "use_int8_vae",
    "use_trt_vae",
    "image_vae",
    "result_format",
    "image_frames",
    "semantic_bridge",
    "semantic_bridge_alpha",
    "fl2va_audio_1",
    "fl2va_audio_2",
    "fl2va_audio_3",
    "encoder_small_input",
)
GENERATION_COMPONENTS = (
    "mode",
    "model_profile",
    "text_encoder",
    "stage_model_offload",
    "generation_mode",
    "turbo_variant",
    "prompt",
    "first",
    "last",
    "ref_image_1",
    "ref_image_2",
    "ref_image_3",
    "ref_image_4",
    "ref_image_5",
    "ref_image_6",
    "ref_image_7",
    "ref_image_8",
    "ref_image_9",
    "ref_video_1",
    "ref_video_2",
    "ref_video_3",
    "ref_audio_1",
    "ref_audio_2",
    "ref_audio_3",
    "duration",
    "width",
    "height",
    "steps",
    "scheduler",
    "seed",
    "attention_mode",
    "sla_preset",
    "sol_tau",
    "sol_thresh_type",
    "sol_exact_mode",
    "sol_dense_steps",
    "sol_step_off",
    "sol_sink_tokens",
    "cache_mode",
    "fbcache_preset",
    "fbcache_threshold",
    "fbcache_start",
    "fbcache_end",
    "fbcache_max_hits",
    "fbcache_temporal_guard",
    "easycache_threshold",
    "easycache_start",
    "easycache_end",
    "easycache_verbose",
    "ref_size",
    "generation_postprocess",
    "reuse_unchanged_inputs",
    "latent_upscale",
    "latent_upscaler_model",
    "latent_upscale_refine_steps",
    "latent_upscale_method",
    "latent_split_tile_width",
    "latent_split_tile_height",
    "latent_split_overlap_ratio",
    "latent_split_fade_ratio",
    "latent_split_chunk_frames",
    "latent_split_temporal_overlap_frames",
    "latent_split_seam_denoise",
    "latent_split_seam_polish",
    "generation_force_offload",
    "generation_split_upscale",
    "generation_split_seconds",
    "generation_upscale_resolution",
    "generation_seedvr2_model",
    "ltx25_model",
    "use_int8_vae",
    "use_trt_vae",
    "image_vae",
    "result_format",
    "image_frames",
    "semantic_bridge",
    "semantic_bridge_alpha",
    "fl2va_audio_1",
    "fl2va_audio_2",
    "fl2va_audio_3",
    "encoder_small_input",
)


@dataclass(frozen=True)
class GenerationArguments:
    values: dict[str, Any]

    @classmethod
    def from_positional(cls, args):
        # Preserve each published boundary as new optional fields are appended.
        if len(args) == GENERATION_FIELDS.index("semantic_bridge"):
            args = (*args, True, 0.10)
        if len(args) == GENERATION_FIELDS.index("fl2va_audio_1"):
            args = (*args, None, None, None)
        if len(args) == GENERATION_FIELDS.index("encoder_small_input"):
            args = (*args, False)
        if len(args) != len(GENERATION_FIELDS):
            raise ValueError(
                f"Expected {len(GENERATION_FIELDS)} generation inputs, received {len(args)}."
            )
        return cls(dict(zip(GENERATION_FIELDS, args, strict=True)))

    @property
    def references(self):
        return {
            kind: tuple(self.values[f"ref_{kind}_{i}"] for i in range(1, count + 1))
            for kind, count in (("image", 9), ("video", 3), ("audio", 3))
        }

    def with_seed(self, seed):
        return replace(self, values={**self.values, "seed": seed})
